"""Developer HTML report — the ``dev`` findings view as a shareable HTML file.

Carries the same information as the terminal ``dev`` report but rendered as a
single self-contained HTML file (embedded CSS, no JavaScript, no external
assets) so it can be attached to a pull request or shared without a terminal.

Where the *security* report groups by severity for triage, this developer view
groups by **file** — the unit a developer actually edits — with findings inside
each file ordered most-severe first. The finding card itself is shared with the
security report via :func:`tf_eu_guard.reporting._html_common.finding_card`.
"""

from pathlib import Path

from tf_eu_guard.models import EnrichedFinding
from tf_eu_guard.reporting._html_common import (
    distinct_files,
    esc,
    finding_card,
    severity_counts,
)
from tf_eu_guard.reporting.styles import DEV_HTML_CSS, SEVERITY_COLOR, SEVERITY_ORDER


def _severity_rank(finding: EnrichedFinding) -> int:
    """Sort key placing the most severe findings first (unknown severities last)."""
    order = {sev: i for i, sev in enumerate(SEVERITY_ORDER)}
    return order.get(finding.severity, len(SEVERITY_ORDER))


def _summary_chips(
    findings: list[EnrichedFinding], unmapped_count: int = 0
) -> str:
    """Render a compact one-line summary (totals + per-severity counts)."""
    counts = severity_counts(findings)
    chips: list[str] = [
        f'<span class="chip"><b>{len(findings)}</b> findings</span>',
        f'<span class="chip"><b>{distinct_files(findings)}</b> files</span>',
    ]
    for sev in SEVERITY_ORDER:
        if counts[sev]:
            chips.append(
                f'<span class="chip" style="border-color:{SEVERITY_COLOR[sev]}">'
                f'<b style="color:{SEVERITY_COLOR[sev]}">{counts[sev]}</b> {esc(sev.value)}</span>'
            )
    if unmapped_count:
        chips.append(
            f'<span class="chip" style="border-color:#7f8c8d">'
            f'<b style="color:#7f8c8d">{unmapped_count}</b> unmapped</span>'
        )
    return '<section class="chips">\n' + "\n".join(chips) + "\n</section>"


def _file_section(file_path: str, group: list[EnrichedFinding]) -> str:
    """Render one file heading plus its findings (most severe first)."""
    group = sorted(group, key=lambda f: (_severity_rank(f), f.check_id))
    n = len(group)
    heading = (
        '<div class="file-group">\n'
        f'<h2 class="file">{esc(file_path)}'
        f'<span class="fcount">{n} finding{"" if n == 1 else "s"}</span></h2>'
    )
    cards = "\n".join(finding_card(f) for f in group)
    return f"{heading}\n{cards}\n</div>"


def _render(
    findings: list[EnrichedFinding],
    *,
    target: str,
    timestamp: str,
    version: str,
    unmapped_count: int = 0,
) -> str:
    """Assemble the complete HTML document."""
    unmapped_span = (
        f"<span>Unmapped Checkov findings: {unmapped_count}</span>"
        if unmapped_count
        else ""
    )
    header = (
        "<header>\n"
        "  <h1>tf-eu-guard &mdash; Developer Report</h1>\n"
        '  <div class="meta">'
        f'<span>Target: <code>{esc(target) or "&mdash;"}</code></span>'
        f"<span>Generated: {esc(timestamp) or '&mdash;'}</span>"
        f"<span>Findings: {len(findings)}</span>"
        f"{unmapped_span}"
        "</div>\n"
        "</header>"
    )

    if not findings and not unmapped_count:
        body = (
            '<div class="empty"><h2 style="margin-top:0">No compliance findings</h2>'
            "<p>Checkov reported no failed checks that map to a NIS2 or GDPR control "
            "for this target.</p></div>"
        )
    elif not findings:
        body = (
            '<div class="empty"><h2 style="margin-top:0">No mapped compliance findings'
            f" &mdash; {unmapped_count} unmapped</h2>"
            "<p>Checkov reported no failed checks that map to a NIS2 or GDPR control, "
            f"but <strong>{unmapped_count}</strong> failed check(s) have no current EU "
            "regulatory mapping and are not shown here. Review them with a plain "
            "Checkov run.</p></div>"
        )
    else:
        # Group by file; files sorted alphabetically for a stable, navigable layout.
        by_file: dict[str, list[EnrichedFinding]] = {}
        for f in findings:
            by_file.setdefault(f.file_path, []).append(f)
        sections = [
            _summary_chips(findings, unmapped_count),
            "<h2>Findings by file</h2>",
        ]
        if unmapped_count:
            sections.append(
                f'<p class="unmapped"><strong>{unmapped_count}</strong> additional '
                "Checkov finding(s) have no current EU regulatory mapping and are not "
                "shown in this report.</p>"
            )
        sections.extend(
            _file_section(path, by_file[path]) for path in sorted(by_file)
        )
        body = "\n".join(sections)

    footer = (
        "<footer>Generated by tf-eu-guard"
        f"{' v' + esc(version) if version else ''}"
        f"{' on ' + esc(timestamp) if timestamp else ''}. "
        "Only failed checks that map to a NIS2/GDPR control are shown; "
        f"{unmapped_count} unmapped Checkov finding(s) "
        "were reported separately; "
        "absence of a finding is not evidence of compliance.</footer>"
    )

    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n<head>\n'
        '<meta charset="utf-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>tf-eu-guard Developer Report</title>\n"
        f"<style>{DEV_HTML_CSS}</style>\n"
        "</head>\n<body>\n"
        f"{header}\n{body}\n{footer}\n"
        "</body>\n</html>\n"
    )


def generate_dev_html_report(
    findings: list[EnrichedFinding],
    *,
    target: str = "",
    timestamp: str = "",
    version: str = "",
    output_path: Path | None = None,
    unmapped_count: int = 0,
) -> str:
    """Generate the self-contained developer HTML report (findings grouped by file).

    Args:
        findings: Enriched findings (as produced by ``enrich_findings``).
        target: Human-readable scan target (shown in the header).
        timestamp: Human-readable scan time (shown in the header/footer).
        version: tf-eu-guard version (shown in the footer).
        output_path: If given, the HTML is also written to this path (UTF-8).
        unmapped_count: Checkov findings with no registry mapping — shown as a
            count so they are present-but-unmapped, not absent.

    Returns:
        The complete HTML document as a string.
    """
    document = _render(
        findings,
        target=target,
        timestamp=timestamp,
        version=version,
        unmapped_count=unmapped_count,
    )
    if output_path is not None:
        Path(output_path).write_text(document, encoding="utf-8")
    return document
